web/src/main/java/edu/tum/cs/wis/view/BundestagBean.java
package edu.tum.cs.wis.view;

import java.util.ArrayList;
import java.util.List;
import java.util.Map.Entry;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.inject.Inject;

import edu.tum.cs.wis.dao.VoteDAO;
import edu.tum.cs.wis.model.Mandat;
import edu.tum.cs.wis.model.Partei;

@ManagedBean(name = "bundestagBean")
@SessionScoped
public class BundestagBean {
	@Inject
	private VoteDAO db;
	
	private List<Mandat> abgeordnete;
	private List<Entry<Partei, Integer>> seatingCache;

	public List<Mandat> getAbgeordnete() {
		if (abgeordnete == null) {
			abgeordnete = db.getAbgeordnete(2009);
		}
		return abgeordnete;
	}
	
	public List<Entry<Partei, Integer>> getTotalSeating() {
		if (seatingCache == null) {
			seatingCache = new ArrayList<Entry<Partei, Integer>>(db.getTotalSeating(2009).entrySet());
		}
		return seatingCache;
	}
}

web/src/main/java/edu/tum/cs/wis/view/GewinnerBean.java
package edu.tum.cs.wis.view;

import java.util.List;
import java.math.BigInteger;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import edu.tum.cs.wis.dao.VoteDAO;
import edu.tum.cs.wis.dao.DefaultVoteDAO;
import edu.tum.cs.wis.model.Bewerber;
import edu.tum.cs.wis.model.Partei;
import edu.tum.cs.wis.model.Quadruple;

@ManagedBean(name = "gewinnerBean")
@SessionScoped
public class GewinnerBean {
	
	// List of winners with number of additional votes and rank
	private List<Quadruple<Bewerber, Partei, BigInteger, Integer>> winners;
	
	private VoteDAO db;
	
	@PostConstruct
	public void init() {
		db = new DefaultVoteDAO();
		winners = db.getKnappsteGewinner(2009);
	}
	
	public List<Quadruple<Bewerber,Partei,BigInteger, Integer>> getWinner() {
		return winners;
	}
}

web/src/main/java/edu/tum/cs/wis/view/UeberhangmandateBean.java
package edu.tum.cs.wis.view;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.inject.Inject;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import edu.tum.cs.wis.dao.VoteDAO;
import edu.tum.cs.wis.model.Bundesland;
import edu.tum.cs.wis.model.Partei;

@ManagedBean(name = "ueberhangmandateBean")
@SessionScoped
public class UeberhangmandateBean {

	// DB session
	@Inject
	private VoteDAO db;
	
	private Map<Partei, Integer> ueberhangMandatePartei;
	private Map<Bundesland, Integer> ueberhangMandateBundesland;

	/**
	 * Get parties with Überhangmandate
	 * 
	 * @return
	 */
	public Collection<Partei> getParteien() {
		return new ArrayList<Partei>(getUeberhangmandateProPartei().keySet());
	}

	/**
	 * Get the map of parties and their number of Überhangmandate (Only parties
	 * with at least one Überhangmandat are returned)
	 * 
	 * @return
	 */
	public Map<Partei, Integer> getUeberhangmandateProPartei() {
		if (ueberhangMandatePartei == null) {
			ueberhangMandatePartei = db.getUeberhangmandateProPartei(2009);
		}
		return ueberhangMandatePartei;
	}

	/**
	 * Get the map of Bundesländer and their number of Überhangmandate (Only
	 * Bundesländer with at least one Überhangmandat are returned)
	 * 
	 * @return
	 */
	public Collection<Bundesland> getBundeslaender() {
		return new ArrayList<Bundesland>(getUeberhangmandateProBundesland().keySet());
	}

	/**
	 * Get the number of Überhangmandate for a specific Bundesland from
	 * getBundeslaender
	 * 
	 * @return
	 */
	public Map<Bundesland, Integer> getUeberhangmandateProBundesland() {
		if (ueberhangMandateBundesland == null) {
			ueberhangMandateBundesland = db.getUeberhangmandateProBundesland(2009,false);
		}
		return ueberhangMandateBundesland;
	}
	
	/**
	 * Create Json mapping for the chart showing the number of Überhangmandate per party
	 * @param jahr
	 * @return
	 */
	public String getJsonUeberhangmandateParteiMapping() {
		Map<String, Integer> mapping = new HashMap<String, Integer>();
		for(Partei partei : getParteien()){
			mapping.put(partei.getName(), getUeberhangmandateProPartei().get(partei));
		}
		return new Gson().toJson(mapping, new TypeToken<Map<String, Integer>>() {}.getType());
	}
}

web/src/main/java/edu/tum/cs/wis/view/UpdateBean.java
package edu.tum.cs.wis.view;

import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.enterprise.inject.Default;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

import edu.tum.cs.wis.dao.UpdateDAO;
  
@ManagedBean
@ViewScoped
public class UpdateBean implements Serializable {  
  
    private Integer progress;  
    private boolean started = false;
    private UpdateThread thread;
    
	@Inject @Default
	private UpdateDAO updateDAO;
  
	@PostConstruct
	public void init(){
		thread = new UpdateThread(updateDAO);
	}
	
    public Integer getProgress() {  
    	if(thread.getProgress() == 100)
    		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Update Completed", "Update Completed"));  
    	return thread.getProgress();
    }  
      
    public String getStatus(){
    	return thread.getStatus();
    }
    public void onUpdate() {  

    }  
    public String start(){
    	if(!started){
    		thread.start();
    		started = true;
    	}
    	return null;
    }
    
    public boolean getStopPoll(){
    	return !(thread.getState() == Thread.State.RUNNABLE);
    }
} 

web/src/main/java/edu/tum/cs/wis/view/WahlkreisBean.java
package edu.tum.cs.wis.view;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.model.SelectItem;
import javax.inject.Inject;

import org.apache.log4j.Logger;

import edu.tum.cs.wis.dao.DVoteDAO;
import edu.tum.cs.wis.dao.VoteDAO;
import edu.tum.cs.wis.model.Bewerber;
import edu.tum.cs.wis.model.Bundesland;
import edu.tum.cs.wis.model.Direktkandidat;
import edu.tum.cs.wis.model.IErststimmen;
import edu.tum.cs.wis.model.IZweitstimmenLandesliste;
import edu.tum.cs.wis.model.Landesliste;
import edu.tum.cs.wis.model.Partei;
import edu.tum.cs.wis.model.Wahlkreis;
import edu.tum.cs.wis.model.ZweitstimmenSieger;

@ManagedBean(name = "wahlkreisBean")
@SessionScoped
public class WahlkreisBean {
	private final Logger log = Logger.getLogger(WahlkreisBean.class);

	private List<Wahlkreis> wahlkreise;
	private List<Direktkandidat> direktkandidaten;
	private List<Direktkandidat> wahlkreisDirektkandidaten;
	private List<Landesliste> wahlkreisLandeslisten;

	private String selectedId;
	private String zweitstimmenCacheSelectedId, erststimmenCacheSelectedId;
	private Wahlkreis selected;
	private int totalSecondVotes;
	private int totalFirstVotes;
	
	private List<IZweitstimmenLandesliste> zweitstimmenCache;
	private List<IErststimmen> erststimmenCache;
	
	private Map<Bewerber, Integer> erststimmen2005;
	private Map<Bewerber, Integer> erststimmen2009;
	private Map<Partei, Integer> zweitstimmen2005;
	private Map<Partei, Integer> zweitstimmen2009;
	
	private Map<Integer, Double> wahlbeteiligung = new HashMap<Integer, Double>(2);
	private List<ZweitstimmenSieger> zweitstimmenSieger2009;
	
	private boolean useAggregatedResults = true;

	private VoteDAO db;
	
	@Inject
	private VoteDAO aggregatedDAO;
	
	@Inject @DVoteDAO
	private VoteDAO directDAO;
	
	
	@PostConstruct
	public void init(){
		// Use aggregated results
		db = aggregatedDAO;
	}
	
	/**
	 * Return how the results are calculated (using aggregated tables or not)
	 * @return true if aggregated results are used
	 */
	public boolean getUsingAggregatedResults(){
		return useAggregatedResults;
	}
	
	/**
	 * Switch calculation method, base on aggregated results / direct calculation
	 */
	public void processSwitchEvent() {
		useAggregatedResults = !useAggregatedResults;
		if (useAggregatedResults)
			db = aggregatedDAO;
		else
			db = directDAO;
		if (useAggregatedResults)
			log.info("Using aggregated DAO");
		else
			log.info("Using direct DAO");

		clear();
	}
	
	private void clear() {
		wahlbeteiligung = new HashMap<Integer, Double>(2);
		erststimmenCache = null;
		zweitstimmenCache = null;
		erststimmenCacheSelectedId = null;
		zweitstimmenCacheSelectedId = null;
		wahlkreisDirektkandidaten = null;
		wahlkreisLandeslisten = null;
		erststimmen2005 = null;
		erststimmen2009 = null;
		zweitstimmen2005 = null;
		zweitstimmen2009 = null;
		
		Collections.sort(getWahlkreisLandeslisten(), new Comparator<Landesliste>() {
			@Override
			public int compare(Landesliste l1, Landesliste l2) {
				final Map<Partei, Integer> results = getZweitstimmen2009();
				final Partei p1 = l1.getPartei();
				final Partei p2 = l2.getPartei();
				
				if (p1 == null || p2 == null) {
					return 0;
				}
				return results.get(p1).compareTo(results.get(p2));
			}
		});
	}

	public String loadWahlkreis() {
		log.info("loadWahlkreis(), selectedId=" + selectedId);
		if (selectedId == null) {
			return "pretty:home";
		}
		try {
			long id = Long.parseLong(selectedId);
			selected = db.getWahlkreis(id);
			
			if (selected == null) {
				return "pretty:home";
			}
			
			clear();
			return null;
		} catch (NumberFormatException e) {
			return "pretty:home";
		}
	}

	public List<IErststimmen> getErststimmen() {
		// Avoid bug of accordion causing several queries when closing a panel
		if(selectedId == erststimmenCacheSelectedId){
			return erststimmenCache;
		}
		
		erststimmenCache = db.fetchErststimmen(selected, 2009);
		erststimmenCacheSelectedId = selectedId;

		totalFirstVotes = 0;
		for (IErststimmen zs : erststimmenCache) {
			totalFirstVotes += zs.getStimmen();
		}

		return erststimmenCache;
	}
	
	private List<IErststimmen> getErststimmen(int year) {
		return db.fetchErststimmen(selected, year);
	}

	public double getWahlbeteiligung(int year) {
		if (!wahlbeteiligung.containsKey(year)) {
			wahlbeteiligung.put(year, db.getWahlbeteiligung(selected, year));
		}
		return wahlbeteiligung.get(year);
	}
	
	public double getWahlbeteiligungsDelta() {
		return getWahlbeteiligung(2009) - getWahlbeteiligung(2005);
	}

	public List<IZweitstimmenLandesliste> getZweitstimmen() {
		// Avoid bug of accordion causing several queries when closing a panel
		if(selectedId == zweitstimmenCacheSelectedId){
			return zweitstimmenCache;
		}
		
		
		zweitstimmenCache = db.fetchZweitstimmen(selected, 2009);
		zweitstimmenCacheSelectedId = selectedId;

		totalSecondVotes = 0;
		for (IZweitstimmenLandesliste zs : zweitstimmenCache) {
			totalSecondVotes += zs.getStimmen();
		}

		return zweitstimmenCache;
	}
	
	private List<IZweitstimmenLandesliste> getZweitstimmen(int year) {
		return db.fetchZweitstimmen(selected, year);
	}

	public List<Direktkandidat> getDirektkandidaten() {
		if (direktkandidaten == null) {
			direktkandidaten = db.getDirektkandidaten(2009);
		}
		return direktkandidaten;
	}
	
	public List<Direktkandidat> getWahlkreisDirektkandidaten() {
		if (wahlkreisDirektkandidaten == null) {
			wahlkreisDirektkandidaten = db.getDirektkandidaten(selected, 2009); 
		}
		return wahlkreisDirektkandidaten;
	}
	
	public List<Landesliste> getWahlkreisLandeslisten() {
		if (wahlkreisLandeslisten == null) {
			wahlkreisLandeslisten = db.getLandeslisten(selected, 2009);
		}
		return wahlkreisLandeslisten;
	}

	public List<Wahlkreis> getWahlkreise() {
		if (wahlkreise == null) {
			wahlkreise = db.getWahlkreise();
		}
		return wahlkreise;
	}

	public ZweitstimmenSieger getZweitstimmenSieger2009() {
		return db.getZweitstimmenSieger(2009, selected);
	}
	
	public ZweitstimmenSieger getZweitstimmenSieger2009(Wahlkreis kreis) {
		if (zweitstimmenSieger2009 == null) {
			zweitstimmenSieger2009 = db.getZweitstimmenSieger(2009);
		}
		
		for (ZweitstimmenSieger zs : zweitstimmenSieger2009) {
			if (zs.getWahlkreis().equals(kreis)) {
				return zs;
			}
		}
		return null;
	}

	public List<SelectItem> getBundeslaender() {
		List<Bundesland> laender = db.getBundeslaender();
		List<SelectItem> result = new ArrayList<SelectItem>(17);
		result.add(new SelectItem(""));
		for (Bundesland bl : laender) {
			result.add(new SelectItem(bl.getName()));
		}
		return result;
	}
	
	public List<Partei> getParteien() {
		return db.getParteien();
	}

	public int getZweitstimmen(Partei partei, int jahr) {
		return db.getZweitstimmen(partei, jahr);
	}

	public String getSelectedId() {
		return selectedId;
	}

	public void setSelectedId(String selectedId) {
		this.selectedId = selectedId;
	}

	public Wahlkreis getSelected() {
		return selected;
	}

	public int getTotalSecondVotes() {
		return totalSecondVotes;
	}

	public int getTotalFirstVotes() {
		return totalFirstVotes;
	}

	public Map<Bewerber, Integer> getErststimmen2005() {
		if (erststimmen2005 == null) {
			erststimmen2005 = new HashMap<Bewerber, Integer>();
			for (IErststimmen es : getErststimmen(2005)) {
				erststimmen2005.put(es.getKandidat().getBewerber(), es.getStimmen());
			}
		}
		return erststimmen2005;
	}

	public Map<Bewerber, Integer> getErststimmen2009() {
		if (erststimmen2009 == null) {
			erststimmen2009 = new HashMap<Bewerber, Integer>();
			totalFirstVotes = 0;
			for (IErststimmen es : getErststimmen(2009)) {
				erststimmen2009.put(es.getKandidat().getBewerber(), es.getStimmen());
				totalFirstVotes += es.getStimmen();
			}
		}
		return erststimmen2009;
	}
	
	public Map<Partei, Integer> getZweitstimmen2005() {
		if (zweitstimmen2005 == null) {
			zweitstimmen2005 = new HashMap<Partei, Integer>();
			for (IZweitstimmenLandesliste zs : getZweitstimmen(2005)) {
				zweitstimmen2005.put(zs.getLandesliste().getPartei(), zs.getStimmen());
			}
		}
		return zweitstimmen2005;
	}

	public Map<Partei, Integer> getZweitstimmen2009() {
		if (zweitstimmen2009 == null) {
			totalSecondVotes = 0;
			zweitstimmen2009 = new HashMap<Partei, Integer>();
			for (IZweitstimmenLandesliste zs : getZweitstimmen(2009)) {
				zweitstimmen2009.put(zs.getLandesliste().getPartei(), zs.getStimmen());
				totalSecondVotes += zs.getStimmen();
			}
		}
		return zweitstimmen2009;
	}
}

web/src/main/webapp/gewinner.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition template="/WEB-INF/templates/default.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pretty="http://ocpsoft.com/prettyfaces">
	<!-- 	<ui:define name="pageTitle">Home</ui:define> -->
	<ui:define name="content">
		<h:form>
			<p:messages showDetail="true" />
			<p:dataTable var="g"
				value="#{gewinnerBean.winner}" rows="15" paginator="true" paginatorPosition="bottom">
				<p:column sortBy="#{g.first.name}">
					<f:facet name="header">Knappste Gewinner</f:facet>
		    		#{g.first.fullName}
		  		</p:column>
		  		<p:column sortBy="#{g.second.name}">
					<f:facet name="header">Partei</f:facet>
		    		#{g.second.name}
		  		</p:column>
		  		<p:column sortBy="#{g.third}">
					<f:facet name="header">Stimmenvorsprung</f:facet>
		    		#{g.third}
		  		</p:column>
				<p:column sortBy="#{g.fourth}">
					<f:facet name="header">Parteirang</f:facet>
		    		#{g.fourth}
		  		</p:column>
			</p:dataTable>
		</h:form>
	</ui:define>
</ui:composition>

web/src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition template="/WEB-INF/templates/default.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">
	<!-- 	<ui:define name="pageTitle">Home</ui:define> -->

	<ui:define name="additionalHeaders">
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>
	</ui:define>

	<ui:define name="content">
		<h:outputScript name="js/charts.js"></h:outputScript>
		<h:outputScript library="primefaces" name="jquery/jquery.js" target="head" />
		
		<h:form>
			<!--Div that will hold the pie chart-->
			<div id="chart_div"></div>
			
			<p:dataTable value="#{bundestagBean.totalSeating}" var="mapping">
				<p:column>
					<f:facet name="header">Partei</f:facet>
					#{mapping.key.name}
				</p:column>
				<p:column>
					<f:facet name="header">Sitze im Bundestag</f:facet>
					#{mapping.value}
				</p:column>
			</p:dataTable>
			
			<script type="text/javascript">
				$(function() {
						drawChart();
					});
			</script>
		</h:form>
	</ui:define>
</ui:composition>

web/src/main/webapp/update.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition template="/WEB-INF/templates/default.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">
	<!-- 	<ui:define name="pageTitle">Home</ui:define> -->


	<ui:define name="content">




		<script type="text/javascript">
			function update() {
				if (pbAjax.getValue() == 100) {
					updatePoll.stop();
					startButton.enable();
				}

			}
		</script>

		<h:form>
			<p:panel>
				<h2>Stimmenaktualisierung</h2>
				<p>Um den Aktualisierungsvorgang zu starten, drücken Sie bitte
					auf Start</p>

				<p:poll interval="3" autoStart="false" oncomplete="update()"
					listener="#{updateBean.onUpdate}" update="update_panel"
					widgetVar="updatePoll" />
				<h:panelGroup id="update_panel">
					<p:progressBar widgetVar="pbAjax" value="#{updateBean.progress}"
						oncomplete="updatePoll.stop();startButton.enable();">
					</p:progressBar>
					<h:outputText value="#{updateBean.status}"></h:outputText>
				</h:panelGroup>
				<div style="margin-top:5px">
					<p:commandButton widgetVar="startButton" value="Start"
						actionListener="#{updateBean.start}"
						onclick="updatePoll.start();startButton.disable()" />
				</div>
			</p:panel>
		</h:form>

	</ui:define>
</ui:composition>

web/src/main/webapp/wahlkreis.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition template="/WEB-INF/templates/default.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">
	<!-- 	<ui:define name="pageTitle">Home</ui:define> -->

	<ui:define name="additionalHeaders">
		<style type="text/css">
#facts {
	margin: 1em 0;
}

#facts li {
	line-height: 1.4em;
}

#method {
	margin-top: 1em;
}
</style>
	</ui:define>

	<ui:define name="content">
		<h:form>
			<h2>#{wahlkreisBean.selected.name}</h2>
			<h3 class="subtitle">(#{wahlkreisBean.selected.bundesland.name})</h3>

			<ul id="facts">
				<li>Direktkandidat 2009:
					#{wahlkreisBean.selected.getDirektmandat(2009).bewerber.fullName}
					(#{wahlkreisBean.selected.getDirektmandatPartei(2009).name})</li>
				<li>Direktkandidat 2005:
					#{wahlkreisBean.selected.getDirektmandat(2005).bewerber.fullName}
					(#{wahlkreisBean.selected.getDirektmandatPartei(2005).name})</li>
				<li>Bevölkerung: #{wahlkreisBean.selected.bevoelkerung}</li>
				<li>Wahlberechtigte: #{wahlkreisBean.selected.wahlberechtigte}</li>
				<li>Wahlbeteiligung 2009: <h:outputText
						value="#{wahlkreisBean.getWahlbeteiligung(2009)}">
						<f:convertNumber type="percent" maxFractionDigits="1" />
					</h:outputText> (<h:outputText value="#{wahlkreisBean.wahlbeteiligungsDelta}">
						<f:convertNumber pattern="+##.0%;-##.0%" />
					</h:outputText>)
				</li>
			</ul>

			<p:accordionPanel dynamic="true">
				<p:tab title="Erststimmen">
					<p:dataTable value="#{wahlkreisBean.wahlkreisDirektkandidaten}"
						var="dk" sortOrder="descending"
						sortBy="#{wahlkreisBean.erststimmen2009[dk.bewerber]}">
						<p:column>
							<f:facet name="header">Bewerber</f:facet>
							#{dk.fullName}
							(#{dk.parteiName})
						</p:column>
						<p:column sortBy="#{wahlkreisBean.erststimmen2009[dk.bewerber]}">
							<f:facet name="header">Erststimmen</f:facet>
							<h:outputText rendered="#{dk.partei != null}" value="#{wahlkreisBean.erststimmen2009[dk.bewerber]}" />
							<h:outputText rendered="#{dk.partei == null}" value="*" />
							
							<h:panelGroup layout="none"
								rendered="#{wahlkreisBean.erststimmen2005[dk.bewerber] != null and wahlkreisBean.erststimmen2005[dk.bewerber] > 0}">
							 (<h:outputText
									value="#{(wahlkreisBean.erststimmen2009[dk.bewerber] - wahlkreisBean.erststimmen2005[dk.bewerber]) * 1.0 / wahlkreisBean.erststimmen2005[dk.bewerber]}">
									<f:convertNumber pattern="+##.0%;-##.0%" />
								</h:outputText>)
							</h:panelGroup>
						</p:column>
						<p:column>
							<f:facet name="header">Erststimmen (%)</f:facet>
							<h:outputText rendered="#{dk.partei != null}"
								value="#{wahlkreisBean.erststimmen2009[dk.bewerber] * 1.0 / wahlkreisBean.totalFirstVotes}">
								<f:convertNumber maxFractionDigits="1" type="percent" />
							</h:outputText>
							<h:outputText rendered="#{dk.partei == null}" value="*" />
						</p:column>
					</p:dataTable>
				</p:tab>
				<p:tab title="Zweitstimmen">
					<p:dataTable value="#{wahlkreisBean.wahlkreisLandeslisten}"
						var="ll" sortOrder="descending"
						sortBy="#{wahlkreisBean.zweitstimmen2009[ll.partei]}">
						<p:column>
							<f:facet name="header">Partei</f:facet>
							#{ll.partei.name}
						</p:column>
						<p:column sortBy="#{wahlkreisBean.zweitstimmen2009[ll.partei]}">
							<f:facet name="header">Zweitstimmen</f:facet>
							#{wahlkreisBean.zweitstimmen2009[ll.partei]}
							<h:panelGroup layout="none"
								rendered="#{wahlkreisBean.zweitstimmen2005[ll.partei] != null and wahlkreisBean.zweitstimmen2005[ll.partei] > 0}">
	               (<h:outputText
									value="#{(wahlkreisBean.zweitstimmen2009[ll.partei] - wahlkreisBean.zweitstimmen2005[ll.partei]) * 1.0 / wahlkreisBean.zweitstimmen2005[ll.partei]}">
									<f:convertNumber pattern="+##.0%;-##.0%" />
								</h:outputText>)
							</h:panelGroup>
						</p:column>
						<p:column>
							<f:facet name="header">Zweitstimmen (%)</f:facet>
							<h:outputText
								value="#{wahlkreisBean.zweitstimmen2009[ll.partei] * 1.0 / wahlkreisBean.totalSecondVotes}">
								<f:convertNumber maxFractionDigits="1" type="percent" />
							</h:outputText>
						</p:column>
					</p:dataTable>
				</p:tab>
			</p:accordionPanel>

			<div id="method">
				Berechnungsmethode:
				<ui:fragment rendered="#{!wahlkreisBean.usingAggregatedResults}">
					<span style='color: #c00'>nicht aggregiert </span>
				</ui:fragment>
				<ui:fragment rendered="#{wahlkreisBean.usingAggregatedResults}">
					<span style='color: #0c0'>aggregiert </span>
				</ui:fragment>

				<h:commandLink action="#{wahlkreisBean.processSwitchEvent}">&#xbb; wechseln</h:commandLink>
				<br />
				* = keine detaillierten Daten für parteilose Kandidaten verfügbar
			</div>
		</h:form>
	</ui:define>
</ui:composition>